# To work with yml please remove properties file both can't be used at a time
# If we have to still applcation can read info from properties file because properties file is high priority

logging:
  level:
    org:
      springframework: info
app:
  name:  Spring World (value form property from dev)
welcome:
  message:  Welcome to ${app.name} from yml file!